4096 root system drwxr-xr-x /TWSE
256 exadm exc drwxrwxr-x /TWSE/bin
256 exadm exc drwxrwxr-x /TWSE/bkbin
256 exadm exc drwxrwxr-x /TWSE/bkcfg
256 twse tse drwxrwxr-- /TWSE/bkfile
66990329 twse tse -rw-rw---- /TWSE/bkfile/ctm7Agent.tar.gz
256 twse tse drwxrwxr-x /TWSE/bklog
256 exadm exc drwxrwxr-x /TWSE/bkshell
256 exadm exc drwxrwxr-x /TWSE/cfg
256 twse tse drwxrwxr-- /TWSE/file
256 twse tse drwxrwxr-x /TWSE/log
256 root system drwxr-xr-x /TWSE/lost+found
256 exadm exc drwxrwxr-x /TWSE/oldbin
256 exadm exc drwxrwxr-x /TWSE/oldcfg
256 exadm exc drwxrwxr-x /TWSE/oldshell
256 exadm exc drwxrwxr-x /TWSE/shell
27826 root system -rwxr-xr-x /TWSE/shell/ib_start.sh
4502 root system -rwxr-xr-x /TWSE/shell/ib_stop.sh
