#!/usr/bin/ksh
./create_FIX1B.sh
./create_FIX2P.sh
./create_FIX3B.sh
./create_FIX4P.sh
./create_FIX5B.sh
./create_FIX6P.sh
./create_FIX7B.sh
./create_FIX8P.sh
./create_FIX9B.sh
./create_FIX10P.sh
./create_TSY.sh
./create_WK.sh
./create_MDS2.sh
./create_LOG2.sh
./create_DAR2.sh
./create_DAP2.sh
./create_vios1.sh
./create_vios2.sh
