#!/usr/bin/ksh
./create_FIX1P.sh
./create_FIX2B.sh
./create_FIX3P.sh
./create_FIX4B.sh
./create_FIX5P.sh
./create_FIX6B.sh
./create_FIX7P.sh
./create_FIX8B.sh
./create_FIX9P.sh
./create_FIX10B.sh
./create_TSX.sh
./create_NIM.sh
./create_MDS1.sh
./create_LOG1.sh
./create_DAR1.sh
./create_DAP1.sh
./create_vios1.sh
./create_vios2.sh
